package defpackage;

/* JADX INFO: compiled from: chromium-ChromePublic.aab-stable-260119 */
/* JADX INFO: loaded from: classes.dex */
public abstract class MI2 {
    public static final Cp a;
    public static final Cp b;
    public static final Cp c;
    public static final Cp d;
    public static final Cp e;
    public static final Cp f;
    public static final Cp g;
    public static final Cp h;
    public static final Cp i;
    public static final Cp j;
    public static final Cp k;
    public static final Cp l;
    public static final Cp m;
    public static final Cp n;
    public static final Cp o;
    public static final Cp p;
    public static final Cp q;

    static {
        Bp bpA = Cp.a();
        bpA.a = 3;
        bpA.b = "Google Play In-app Billing API version is less than 3";
        a = bpA.a();
        Bp bpA2 = Cp.a();
        bpA2.a = 3;
        bpA2.b = "Google Play In-app Billing API version is less than 9";
        bpA2.a();
        Bp bpA3 = Cp.a();
        bpA3.a = 3;
        bpA3.b = "Billing service unavailable on device.";
        b = bpA3.a();
        Bp bpA4 = Cp.a();
        bpA4.a = 5;
        bpA4.b = "Client is already in the process of connecting to billing service.";
        c = bpA4.a();
        Bp bpA5 = Cp.a();
        bpA5.a = 5;
        bpA5.b = "The list of SKUs can't be empty.";
        bpA5.a();
        Bp bpA6 = Cp.a();
        bpA6.a = 5;
        bpA6.b = "SKU type can't be empty.";
        d = bpA6.a();
        Bp bpA7 = Cp.a();
        bpA7.a = 5;
        bpA7.b = "Product type can't be empty.";
        e = bpA7.a();
        Bp bpA8 = Cp.a();
        bpA8.a = -2;
        bpA8.b = "Client does not support extra params.";
        f = bpA8.a();
        Bp bpA9 = Cp.a();
        bpA9.a = 5;
        bpA9.b = "Invalid purchase token.";
        bpA9.a();
        Bp bpA10 = Cp.a();
        bpA10.a = 6;
        bpA10.b = "An internal error occurred.";
        g = bpA10.a();
        Bp bpA11 = Cp.a();
        bpA11.a = 5;
        bpA11.b = "SKU can't be null.";
        bpA11.a();
        Bp bpA12 = Cp.a();
        bpA12.a = 0;
        h = bpA12.a();
        Bp bpA13 = Cp.a();
        bpA13.a = -1;
        bpA13.b = "Service connection is disconnected.";
        i = bpA13.a();
        Bp bpA14 = Cp.a();
        bpA14.a = 2;
        bpA14.b = "Timeout communicating with service.";
        j = bpA14.a();
        Bp bpA15 = Cp.a();
        bpA15.a = -2;
        bpA15.b = "Client does not support subscriptions.";
        k = bpA15.a();
        Bp bpA16 = Cp.a();
        bpA16.a = -2;
        bpA16.b = "Client does not support subscriptions update.";
        bpA16.a();
        Bp bpA17 = Cp.a();
        bpA17.a = -2;
        bpA17.b = "Client does not support get purchase history.";
        l = bpA17.a();
        Bp bpA18 = Cp.a();
        bpA18.a = -2;
        bpA18.b = "Client does not support price change confirmation.";
        bpA18.a();
        Bp bpA19 = Cp.a();
        bpA19.a = -2;
        bpA19.b = "Play Store version installed does not support cross selling products.";
        bpA19.a();
        Bp bpA20 = Cp.a();
        bpA20.a = -2;
        bpA20.b = "Client does not support multi-item purchases.";
        m = bpA20.a();
        Bp bpA21 = Cp.a();
        bpA21.a = -2;
        bpA21.b = "Client does not support offer_id_token.";
        n = bpA21.a();
        Bp bpA22 = Cp.a();
        bpA22.a = -2;
        bpA22.b = "Client does not support ProductDetails.";
        o = bpA22.a();
        Bp bpA23 = Cp.a();
        bpA23.a = -2;
        bpA23.b = "Client does not support in-app messages.";
        bpA23.a();
        Bp bpA24 = Cp.a();
        bpA24.a = -2;
        bpA24.b = "Client does not support user choice billing.";
        bpA24.a();
        Bp bpA25 = Cp.a();
        bpA25.a = -2;
        bpA25.b = "Play Store version installed does not support external offer.";
        bpA25.a();
        Bp bpA26 = Cp.a();
        bpA26.a = 5;
        bpA26.b = "Unknown feature";
        bpA26.a();
        Bp bpA27 = Cp.a();
        bpA27.a = -2;
        bpA27.b = "Play Store version installed does not support get billing config.";
        bpA27.a();
        Bp bpA28 = Cp.a();
        bpA28.a = -2;
        bpA28.b = "Query product details with serialized docid is not supported.";
        bpA28.a();
        Bp bpA29 = Cp.a();
        bpA29.a = 4;
        bpA29.b = "Item is unavailable for purchase.";
        p = bpA29.a();
        Bp bpA30 = Cp.a();
        bpA30.a = -2;
        bpA30.b = "Query product details with developer specified account is not supported.";
        bpA30.a();
        Bp bpA31 = Cp.a();
        bpA31.a = -2;
        bpA31.b = "Play Store version installed does not support alternative billing only.";
        bpA31.a();
        Bp bpA32 = Cp.a();
        bpA32.a = 5;
        bpA32.b = "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.";
        q = bpA32.a();
    }

    public static Cp a(int i2, String str) {
        Bp bpA = Cp.a();
        bpA.a = i2;
        bpA.b = str;
        return bpA.a();
    }
}
